project-root/
  package.json
  tsconfig.json
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts

  src/
    main.tsx
    types/
      global.d.ts
    state/
      settings-store.ts
      stream-store.ts
      bot-store.ts
      auth-store.ts
    pages/
      DashboardPage.tsx
      SettingsPage.tsx
      AuthPage.tsx
    components/
      layout/
        AppShell.tsx
        Sidebar.tsx
      dashboard/
        PriceChart.tsx
        PnlChart.tsx
        OrderHistory.tsx
        BotControl.tsx
      settings/
        ModeSelector.tsx
        ApiKeyForm.tsx
    router/
      index.tsx

  electron/
    main/
      main.ts
      ipc/
        ipc-trading-stream.ts
        ipc-bot-control.ts
        ipc-mode.ts
        ipc-settings.ts
      core/
        trading/
          engine/
            trading-orchestrator.ts
            orchestrator-manager.ts
            price-feed.ts
            strategy-engine.ts
            risk-manager.ts
          config/
            pairs-config.ts
        broker/
          broker-types.ts
          broker-demo-adapter.ts
          broker-live-adapter.ts
          broker-client.ts
        settings/
          live-config-store.ts
        storage/
          user-store.ts
    preload/
      preload.ts
